str = input().split()
A = float(str[0])
B = float(str[1])
C = float(str[2])
print('TRIANGULO: {:.3f}'.format((A*C)/2))
print('CIRCULO: {:.3f}'.format(3.14159 * C * C))
print('TRAPEZIO: {:.3f}'.format(((A+B)/2)*C))
print('QUADRADO: {:.3f}'.format(B*B))
print('QUADRADO: {:.3f}'.format(B*B))